export default {
    SET_STATE: 'SET_STATE',
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    ERROR: 'ERROR',
    GET_POSTS: 'GET_POSTS',
    GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
    SELL_POST: 'SELL_POST',
    SELL_POST_SUCCESS: 'SELL_POST_SUCCESS',
    VERIFY_TOKEN: 'VERIFY_TOKEN',
    GET_USER: 'GET_USER',
    GET_SINGLE_POST: 'GET_SINGLE_POST',
    POST_COMMENT: 'POST_COMMENT',
    LIKE_POST: 'LIKE_POST'
}